version: "3.8"
services:
  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    container_name: products
    ports:
      - "8001:8001"
    depends_on:
      - nosql-db
    volumes:
      - .:/app
      - /app/products/node_modules
    env_file:
      - path: ./customer/.env